import { BookSaleType } from "@/types/table";

export const tableContent: BookSaleType[] = [
    {
        id: 0,
        date: "Jan 12, 2026 14:45",
        buyerName: "Sarah Chen",
        email: "sarah@example.com",
        bookTitle: "Faith & Power",
        quantity: 2,
        amount: "$40.00",
        method: "PayPal",
        reference: "PP-BK-778899",
        enteredBy: "System",
        status: "Completed",
    },
    {
        id: 1,
        date: "Jan 11, 2026 10:20",
        buyerName: "John Adebayo",
        email: "john.a@ade.com",
        bookTitle: "The Prayer Warrior",
        quantity: 1,
        amount: "$15.00",
        method: "Zelle",
        reference: "ZL-BK-112233",
        enteredBy: "Admin",
        status: "Completed",
    },
    {
        id: 2,
        date: "Jan 10, 2026 16:15",
        buyerName: "Michael Roberts",
        email: "m.robs@church.org",
        bookTitle: "Walking in Grace",
        quantity: 5,
        amount: "$75.00",
        method: "PayPal",
        reference: "PP-BK-445566",
        enteredBy: "System",
        status: "Completed",
    },
    {
        id: 3,
        date: "Jan 09, 2026 13:00",
        buyerName: "Elena Rodriguez",
        email: "elena.r@gmail.com",
        bookTitle: "Faith & Power",
        quantity: 10,
        amount: "$180.00",
        method: "Zelle",
        reference: "ZL-BK-998877",
        enteredBy: "Admin",
        status: "Pending",
    },
];
