import { RecentActivityType } from "@/types/table";

export const tableContent: RecentActivityType[] = [
    {
        id: 0,
        date: "Jan 12, 2026 14:22",
        name: "John Adebayo",
        type: "Donation",
        description: "General Donation",
        amount: "$50.00",
        method: "PayPal",
        source: "Auto",
        status: "Completed",
    },
    {
        id: 1,
        date: "Jan 12, 2026 13:45",
        name: "Sarah Chen",
        type: "Book Sale",
        description: "Faith & Power (Book)",
        amount: "$35.00",
        method: "Zelle",
        source: "Manual",
        status: "Completed",
    },
    {
        id: 2,
        date: "Jan 11, 2026 18:10",
        name: "Michael Roberts",
        type: "Donation",
        description: "Building Fund",
        amount: "$200.00",
        method: "PayPal",
        source: "Auto",
        status: "Completed",
    },
    {
        id: 3,
        date: "Jan 11, 2026 16:30",
        name: "Elena Rodriguez",
        type: "Book Sale",
        description: "The Prayer Warrior (Book)",
        amount: "$25.00",
        method: "Zelle",
        source: "Auto",
        status: "Pending",
    },
    {
        id: 4,
        date: "Jan 11, 2026 10:15",
        name: "David Smith",
        type: "Donation",
        description: "General Donation",
        amount: "$100.00",
        method: "PayPal",
        source: "Manual",
        status: "Completed",
    },
    {
        id: 5,
        date: "Jan 10, 2026 21:05",
        name: "Grace Wilson",
        type: "Book Sale",
        description: "Spiritual Growth (Book)",
        amount: "$40.00",
        method: "Zelle",
        source: "Auto",
        status: "Completed",
    },
    {
        id: 6,
        date: "Jan 10, 2026 15:20",
        name: "Samuel Okafor",
        type: "Donation",
        description: "Missions Support",
        amount: "$75.00",
        method: "PayPal",
        source: "Auto",
        status: "Completed",
    },
    {
        id: 7,
        date: "Jan 10, 2026 09:12",
        name: "Linda Thompson",
        type: "Book Sale",
        description: "Faith & Power (Book)",
        amount: "$35.00",
        method: "Zelle",
        source: "Manual",
        status: "Pending",
    },
    {
        id: 8,
        date: "Jan 09, 2026 17:45",
        name: "Christopher Lee",
        type: "Donation",
        description: "Youth Ministry",
        amount: "$150.00",
        method: "PayPal",
        source: "Auto",
        status: "Completed",
    },
    {
        id: 9,
        date: "Jan 09, 2026 12:30",
        name: "Amanda Johnson",
        type: "Book Sale",
        description: "The Prayer Warrior (Book)",
        amount: "$25.00",
        method: "Zelle",
        source: "Auto",
        status: "Completed",
    },
];
