import { DonationType } from "@/types/table";

export const tableContent: DonationType[] = [
    {
        id: 0,
        date: "Jan 12, 2026 14:22",
        donorName: "John Adebayo",
        email: "john.adebayo@example.com",
        amount: "$50.00",
        method: "PayPal",
        reference: "PP-12345678",
        enteredBy: "System",
        status: "Completed",
    },
    {
        id: 1,
        date: "Jan 11, 2026 09:15",
        donorName: "Sarah Chen",
        email: "sarah.chen@example.com",
        amount: "$100.00",
        method: "Zelle",
        reference: "Z-98765432",
        enteredBy: "Admin",
        status: "Completed",
    },
    {
        id: 2,
        date: "Jan 10, 2026 18:30",
        donorName: "Michael Roberts",
        email: "m.roberts@church.org",
        amount: "$250.00",
        method: "PayPal",
        reference: "PP-87654321",
        enteredBy: "System",
        status: "Completed",
    },
    {
        id: 3,
        date: "Jan 09, 2026 11:45",
        donorName: "Elena Rodriguez",
        email: "elena.r@gmail.com",
        amount: "$25.00",
        method: "Zelle",
        reference: "Z-12348765",
        enteredBy: "Admin",
        status: "Pending",
    },
    {
        id: 4,
        date: "Jan 08, 2026 15:20",
        donorName: "David Smith",
        email: "dsmith@services.net",
        amount: "$1,000.00",
        method: "PayPal",
        reference: "PP-11223344",
        enteredBy: "System",
        status: "Completed",
    },
];
